# Generated by Django 2.2.17 on 2021-01-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('romm_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='romm',
            old_name='romm_name',
            new_name='room_name',
        ),
        migrations.RenameField(
            model_name='romm',
            old_name='romm_volume',
            new_name='room_volume',
        ),
    ]
